### ISSUE TITLE
noVNC Seemingly rejecting VNC connections & some installation observations

### ISSUE THREAD

**Issue by m1baldwin** [Open-UAV/openuav-turbovnc#4]
I have recently installed this project on a google compute platform to test the capability after reading the arXiv paper. I followed the posted instructions in the top-level readme. I have run into a couple of issues. Currently, when attempting to connect to the noVNC instance on the VM on port 40001, I am getting the message <remote-client-ip>: ignoring socket not ready. I have tried multiple different VNC clients on different workstations (ubuntu and windows) but no luck. 

Here is what I get when I run "run.sh" and then try to connect (hostnames and IP's omitted):

user@instance-1:~/openuav-build/openuav-turbovnc$ sudo ./run.sh 
+ chmod -f 777 /tmp/.X11-unix
+ rm -rf '/tmp/.X*-lock'
+ rm -rf /tmp/.X11-unix/X0
rm: cannot remove '/tmp/.X11-unix/X0': Device or resource busy
+ touch /root/.Xauthority
+ xauth generate :0 . trusted
+ /opt/TurboVNC/bin/vncserver -SecurityTypes None

Desktop 'TurboVNC: unix:1 ()' started on display unix:1

Starting applications specified in /root/.vnc/xstartup.turbovnc
Log file is /root/.vnc/unix:1.log

+ '[' 0 -eq 0 ']'
+ /opt/noVNC/utils/launch.sh --vnc localhost:5901 --cert /root/self.pem --listen 40001
Using local websockify at /opt/noVNC/utils/websockify/run
Starting webserver and WebSockets proxy on port 40001
WebSocket server settings:
  - Listen on :40001
  - Flash security policy server
  - Web server. Web root: /opt/noVNC
  - SSL/TLS support
  - proxying from :40001 to localhost:5901

Navigate to this URL:

    http://96fa96000f63:40001/vnc.html?host=96fa96000f63&port=40001

Press Ctrl-C to exit

REMOTE: ignoring socket not ready

When I open an interactive terminal in the container, and check what processes are running, I get the following:
root@96fa96000f63:~# ps -aux 
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.5  0.0   1152     4 pts/0    Ss   22:03   0:00 /sbin/docker-init -- /bin/sh -c /usr/local/bin/start_desktop.sh
root         6  0.0  0.0   4504   740 pts/0    S+   22:03   0:00 /bin/sh -c /usr/local/bin/start_desktop.sh
root         7  0.0  0.0  18032  2956 pts/0    S+   22:03   0:00 /bin/bash -x /usr/local/bin/start_desktop.sh
root        21  0.4  0.0  96720 26000 pts/0    S+   22:03   0:00 /opt/TurboVNC/bin/Xvnc :1 -desktop TurboVNC: unix:1 () -httpd /opt/TurboVNC/bin//../java -auth /root/.Xauthority -geometry 1240x900 -depth 24 -rfbwait 120000 -securit
root        27  0.0  0.0  24492  1316 pts/0    S+   22:03   0:00 /opt/TurboVNC/bin/tvncconfig
root        31  0.0  0.0  18080  3008 pts/0    S+   22:03   0:00 bash /opt/noVNC/utils/launch.sh --vnc localhost:5901 --cert /root/self.pem --listen 40001
root        34  0.4  0.0 268128 22984 pts/0    Sl+  22:03   0:00 /usr/bin/lxsession -s Lubuntu
root        42  2.6  0.0 392836 26828 pts/0    Sl+  22:03   0:00 python /opt/noVNC/utils/websockify/run --web /opt/noVNC/utils/../ --cert /root/self.pem 40001 localhost:5901
root        55  0.2  0.0 228600 17348 pts/0    S+   22:03   0:00 openbox --config-file /root/.config/openbox/lubuntu-rc.xml
root        57  0.4  0.0 655240 26268 pts/0    Sl+  22:03   0:00 lxpanel --profile Lubuntu
root        64  0.4  0.0 475808 33468 pts/0    Sl+  22:03   0:00 pcmanfm --desktop --profile lubuntu
root       406  0.0  0.0 120164  6572 ?        Sl   22:03   0:00 /usr/lib/menu-cache/menu-cached /root/.cache/menu-cached-:1
root       413  0.0  0.0  43600   368 pts/0    S+   22:03   0:00 dbus-launch --autolaunch=6db3c9fa5bf34fac8cbf4d391965b5d1 --binary-syntax --close-stderr
root       414  0.0  0.0  42876  3068 ?        Ss   22:03   0:00 /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
root       419  0.0  0.0 641876 13956 ?        Sl   22:03   0:00 /usr/lib/indicator-sound-gtk2/indicator-sound-service
root       421  0.0  0.0 502636  7820 ?        Sl   22:03   0:00 /usr/lib/x86_64-linux-gnu/indicator-application-service
root       432  0.0  0.0 271504  5688 ?        Sl   22:03   0:00 /usr/lib/gvfs/gvfsd
root       439  0.7  0.0  18916  4004 pts/1    Ss   22:03   0:00 /bin/bash
root       528  0.0  0.0  34424  2876 pts/1    R+   22:03   0:00 ps -aux

A couple observations/questions:
1. I don't see nginx running; is it supposed to be running as a process by default, or is there another command that needs to be run to start it? Also, I could not find the nginx config file anywhere, so I could not use the template file provided in the readme for setting up the port/subdomain mapping.
2. Running the instructions as is was causing a failure at the "run.sh" step. The feedback was that there was a mismatch between the Nvidia driver version and the Cuda toolkit being used. It told me to either upgrade the driver or use an earlier container version. I tried installing 384.111 from the nvidia driver source, since this page: https://github.com/NVIDIA/nvidia-docker/wiki/CUDA suggested that for a Tesla series GPU, with a toolkit of >=10.0, should use that. After installing and re-running the build script, run.sh worked. Is this alright?
3. Initially noVNC was not responding to the remote connection at all; since I was using a vanilla google compute VM, I had to add an extra firewall rule to allow tcp traffic to the VM on port 40001. After doing this, I started getting the ignoring socket message. I can see now with wireshark that when my pc sends the request, it gets a response from the vm, but past that nothing of note. 
4. How is unity being run? Is it handled automatically by the run script, or are there other commands?

**Comment by harishanand95** [comment]
Hi,

If you go to instance_public_ip_address:40001 on google cloud, you should be able to see a running container session.

2. Our Dockerfile code here, reflects that of OpenUAV setup in RTX 2080 Ti for cps-vo.org (https://openuav.us/#cpsvo). From what I understand, you have solved the issue. Yes, your setup should be okay, as long as nvcc and nvidia-smi commands shows cuda support. I will update the Dockerfile, with the necessary changes. The change in Dockerfile is to update base image from `nvidia/cudagl:10.0-base-ubuntu16.04` to `nvidia/cudagl:10.1-base-ubuntu16.04`

1. Nginx is required if you wish to setup multiple containers accessible through a single domain. For example, if you have 2 containers running, they can be accessed as term-1.openuav.us and term-2.openuav.us. This would disable any direct port access to machine (like 40001), as the only entry will be through Nginx 443. The template provided should be added as server block to a basic nginx config. Let me know if you need help here.

3. You need to open port 40001 on google cloud instance to view the session.

4. We are working on containerizing Unity process. Currently, we use the Unity setup in an on-premise server as mentioned in paper. ROS-Sharp (https://github.com/siemens/ros-sharp) is used to communicate from unity to container.

**Comment by m1baldwin** [comment]
Thanks, your notes are helpful! One other question about unity; can it just be run on the host and shared across multiple containers simultaneously? Or, must it be installed on each container? 

On the vnc topic, I already have port 40001 open on gcp, however for some reason the noVNC instance in the container is closing the connection almost as soon as it is being initiated. I have confirmed this is seemingly an issue on the container side as the error message in the web browser is saying the target closed the connection. Have you seen this before? Is there a version requirement between the client/server for noVNC?

**Comment by harishanand95** [comment]
Yes, Unity must be installed on the host. You can give IP address of the container and port 9090 to ROS-Sharp plugin to communicate with Unity.
I have fixed the issue, can you try the new commit to setup instance?

**Comment by m1baldwin** [comment]
Sorry, I am a bit confused; the change to the install_nvidia_drivers script looks to match what I had to do, so that looks good. Are you suggesting to use the docker container linked for the dreamlab docker repo instead of the autonomous_sys_build?

**Comment by m1baldwin** [comment]
I have at least got the vnc part working now; I realized that when you said to navigate to the gcp_ip:40001 you meant to do so in  a web browser, not by setting up novnc on local machine and pointing to it. vnc is new for me so my apologies for dragging this out. 

The script you added in the latest commit matches exactly the modification I had to make; I do not have another machine to do a fresh install on, but if I have time I can reset the one I do have and test how it works from fresh at some point in the near future

**Comment by harishanand95** [comment]
If the containers are running, you can use a web browser in you local machine and go to https://<public_ip_of_the_instance>:40001 and Lubuntu desktop.

**Comment by harishanand95** [comment]
@m1baldwin Regarding Unity environment setup, you can try installing Unity inside the containers using their linux build. We will update the repo with more instructions on how to setup Unity.
