### ISSUE TITLE
Getting graphics to work in container desktop

### ISSUE THREAD

**Issue by m1baldwin** [Open-UAV/openuav-turbovnc#7]
After installing and running the container in a google cloud instance based on the provided instructions, I am getting the following issues when trying to run any graphics on the desktop over noVNC.

I used the glxgears to test if I could benchmark the gpu resource on the host.  When I run another graphics application like gazebo I also see a similar message. Trying to run qground-control as user also results in no ui or application opening up either. 

root@c3b9cbdc5ca2:~# vglrun glxgears
No protocol specified
[VGL] ERROR: Could not open display :0.
root@c3b9cbdc5ca2:~# vglrun -d :1 glxgears
Xlib:  extension "GLX" missing on display ":1".
Error: couldn't get an RGB, Double-buffered visual

![Screenshot from 2020-04-03 17-15-03](https://user-images.githubusercontent.com/35272783/78406117-f1956000-75cf-11ea-9bcd-80ade7aacba1.png)

I can see that if I run one of the examples included in the container, the ros-stack seems to be running. However, I have so far been unable to visualize it. Is there an additional step or setup needed here? Or, are the graphics supposed to be viewed in another way?

**Comment by harishanand95** [comment]
I'm not sure what's happening here. 
Can you test `glxgears` without vglrun and display specification?
The parameters for DISPLAY should be set already in the environment to `:1.0`.

Also if its not set properly, I think the issue is on the docker build. Try 
`docker build --no-cache -t autonomous_sys_build autonomous_sys_build`

Recommended: Try doing the docker build on our latest repo as we have fixed an issue regarding Firefox and hence replaced it with Chrome. #6

**Comment by m1baldwin** [comment]
The $DISPLAY var is set to :1.0 as expected, and running just glxgears gives:

No protocol specified
[VGL] ERROR: Could not open display :0

I did notice that when running the run.sh, there is an error with one of the steps on the host: 
rm: cannot remove '/tmp/.X11-unix/X0' : Device or resource busy

Is this related?

**Comment by harishanand95** [comment]
No, it has been added to remove any previous `/tmp/.X11-unix/X0` files in the directory.

You can try docker restart <container_name> and see if it helps.

I'm not clear on what's happening, I would suggest a new docker build `docker build --no-cache -t autonomous_sys_build autonomous_sys_build` if the previous command made no difference.

**Comment by m1baldwin** [comment]
I think I got it to work. I re-ran the script add_xhost.sh before running the "run.sh" script to start the container. After doing that, I am now able to run gpu benchmarking tools and gazebo. I am using a google cloud platform resource, so likely what is being set by add_xhost is being unset when I stop/start the vm, as this brings the VM up/down. 

Thank you for your help with this!
